# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\AdvancedSettings.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from GUI.skeleton.AdvancedSettingsSkeleton import Ui_Form

class AdvancedSettings(QtWidgets.QWidget, Ui_Form):

    switch_basic_settings = QtCore.pyqtSignal()
    switch_output_settings = QtCore.pyqtSignal()
    switch_calibration_settings = QtCore.pyqtSignal()

    def __init__(self):
        QtWidgets.QWidget.__init__(self)
        self.setupUi(self)

        self.back.clicked.connect(self.basicsettingsbutton_handler)
        self.Output_test.clicked.connect(self.switch_output_settings)
        self.Calibration.clicked.connect(self.switch_calibration_settings)

    def basicsettingsbutton_handler(self):
        self.switch_basic_settings.emit()

    def outputsettingsbutton_handler(self):
        self.switch_output_settings.emit()

    def calibrationsettingsbutton_handler(self):
        self.switch_calibration_settings.emit()